[build]
  functions = "netlify/functions"
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
[functions."cache-colecoes"]
  schedule = "*/10 * * * *"
[functions."botconversa"]
  timeout = 26
[functions."logistica-painel"]
  timeout = 26
[functions."logistica-atrasos"]
  schedule = "0 13 * * 1-5"
[functions."logistica-bot"]
  timeout = 26
