[build]
  functions = "netlify/functions"
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
[functions."cache-colecoes"]
  schedule = "*/10 * * * *"
[functions."botconversa"]
  timeout = 26
